name: A workflow for my Moncc deploy
on: push

jobs:
  deploy:
    name: Moncc deploy action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./moncc-deploy
        env:
          MONCC_USER: ${{ secrets.MONCC_USER }}
          MONCC_PASS: ${{ secrets.MONCC_PASS }}
          MONCCODE: ${{ secrets.MONCCODE }}
